import { useState } from "react";
import { useQuery, useAction } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Brain, Loader2, Sparkles, Target, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";

export default function LearningPathsPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const currentYear = useQuery(api.academicYears.getCurrentAcademicYear);
  const paths = useQuery(api.learningPaths.getLearningPaths, {});
  const generateLearningPath = useAction(api.learningPaths.generateLearningPath);
  const user = useQuery(api.users.getMe); // Assume this exists or use auth info

  const handleGenerate = async () => {
    if (!currentYear || !user) return;
    setIsGenerating(true);
    try {
      await generateLearningPath({
        studentId: user._id,
        academicYearId: currentYear._id,
      });

      toast.success("New personalized learning path generated successfully!");
    } catch (e: any) {
      toast.error(e.message || "Failed to generate learning path.");
    } finally {
      setIsGenerating(false);
    }
  };

  if (paths === undefined || user === undefined) {
    return <div className="flex justify-center p-8"><Loader2 className="h-8 w-8 animate-spin" /></div>;
  }

  const activePath = paths.length > 0 ? paths[0] : null;
  let parsedPlan = null;
  
  if (activePath) {
    try {
      // Find the first { and last } to extract ONLY the JSON object
      const startIdx = activePath.plan.indexOf('{');
      const endIdx = activePath.plan.lastIndexOf('}');
      
      if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
        const jsonStr = activePath.plan.substring(startIdx, endIdx + 1);
        parsedPlan = JSON.parse(jsonStr);
      } else {
        throw new Error("No JSON object found in the AI response.");
      }
    } catch (e) {
      console.error("Failed to parse AI plan", e);
      console.error("Raw string was:", activePath.plan);
      parsedPlan = {
        overview: "The AI generated a response, but it was not formatted correctly as JSON. Please try generating it again.",
        focusAreas: []
      };
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
            <Brain className="h-8 w-8 text-primary" />
            AI Learning Path
          </h1>
          <p className="text-muted-foreground mt-1">
            Your personalized weekly study guide, generated by AI based on your performance.
          </p>
        </div>
        {(user?.role === "student" || user?.role === "admin") && (
          <Button onClick={handleGenerate} disabled={isGenerating || !currentYear} className="gap-2">
            {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            Generate New Path
          </Button>
        )}
      </div>

      {activePath && parsedPlan ? (
        <div className="grid gap-6 md:grid-cols-3">
          <Card className="md:col-span-3 bg-primary/5 border-primary/20">
            <CardContent className="p-6">
              <h2 className="text-lg font-semibold text-primary mb-2 flex items-center gap-2">
                <Sparkles className="h-5 w-5" /> AI Overview
              </h2>
              <p className="text-muted-foreground">{parsedPlan.overview}</p>
            </CardContent>
          </Card>

          {(parsedPlan?.focusAreas || []).map((area: any, idx: number) => (
            <Card key={idx} className="border-t-4 border-t-primary">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg flex items-center gap-2">
                  <Target className="h-5 w-5 text-primary" />
                  {area.topic}
                </CardTitle>
                <CardDescription>{area.reason}</CardDescription>
              </CardHeader>
              <CardContent>
                <h4 className="font-medium text-sm mb-3">Recommended Activities:</h4>
                <ul className="space-y-2">
                  {(area?.activities || []).map((act: string, i: number) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <CheckCircle2 className="h-4 w-4 text-emerald-500 mt-0.5 shrink-0" />
                      <span>{act}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card className="border-dashed py-12">
          <CardContent className="flex flex-col items-center justify-center text-center">
            <div className="bg-primary/10 w-16 h-16 rounded-full flex items-center justify-center mb-4">
              <Brain className="h-8 w-8 text-primary" />
            </div>
            <h3 className="text-xl font-bold mb-2">No Learning Path Found</h3>
            <p className="text-muted-foreground mb-6 max-w-sm">
              Generate your first personalized learning path to get AI-powered study recommendations tailored just for you.
            </p>
            <Button onClick={handleGenerate} disabled={isGenerating || !currentYear} size="lg" className="gap-2">
              {isGenerating ? <Loader2 className="h-5 w-5 animate-spin" /> : <Sparkles className="h-5 w-5" />}
              Generate Path
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
